---

- hosts: "{{ host_var|default([]) }}"
  gather_facts: false

  tasks:
    - name: Create VLAN
      cisco.nxos.nxos_vlans:
        config:
        - vlan_id: 172
          name: ACCESS_VLAN
        state: merged

    - name: Configure access VLAN
      cisco.nxos.nxos_l2_interfaces:
        config:
        - name: Ethernet1/4
          access:
            vlan: 172
        state: merged

    - name: Unshut interface
      cisco.nxos.nxos_config:
        lines:
        - no shutdown
        parents: interface ethernet1/4

    - name: Configure VLAN interface
      cisco.nxos.nxos_config:
        lines:
        - feature interface-vlan
        - interface vlan 172
        - ip address {{ interface_ip }} 255.255.255.0 
        - no shutdown
