- name: Delete the topology
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cml_lab_file: data/BRKOPS-2317_DIGITAL-TWIN.yaml
    cml_lab: BRKOPS-2317_DIGITAL-TWIN
    startup: 'all'
    wait: 'no'
    cml_login: &cml_login
      host: 10.122.49.111
      user: admin
      password: C!sco123

  tasks:
    - name: Check for the lab file # Check lab file exists
      ansible.builtin.stat:
        path: "{{ cml_lab_file }}"
      register: stat_result
      delegate_to: localhost

    - name: Check for the CML host, credentials, and topology file # Check CML host, credentials, and topology file are defined
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists
          - cml_login.host != ""
          - cml_login.user != ""
          - cml_login.password != ""
          - cml_lab != ""
        msg: "CML host, credentials, and topology file are required.  Verify the requirements in README are met."
      delegate_to: localhost

    - name: Delete the lab # Create the lab
      cisco.cml.cml_lab:
        <<: *cml_login
        lab: "{{ cml_lab }}"
        state: "absent"
        file: "{{ cml_lab_file }}"
        topology: "{{ lookup('template', cml_lab_file) }}"
      register: results
